<a href="https://colab.research.google.com/github/bimald986-cell/90-Days-of-AI/blob/main/day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

candidates = {
    "Name": ["Asha", "Ravi", "Maya", "Omar", "Sara", "Daniel"],
    "Subject": ["Math", "English", "Science", "Math", "English", "Science"],
    "Experience": [5, 2, 7, 3, 6, 4],
    "ExpectedSalary": [1200, 900, 1500, 1100, 1300, 1250]
}

df = pd.DataFrame(candidates)

In [4]:
filter = df[df(candidates[
    (candidates["subject"].isin(["Math", "Science"]))
    & (candidates["experience"] >= 4)]
sorted_data = filtered.sort_values(
    "experience",
    ascending=False
)

result = sorted_data[["Name", "Subject", "Experience"]]

result]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' on line 1 (194003265.py, line 11)

In [5]:
filtered = df[
    (df["Subject"].isin(["Math", "Science"]))
    & (df["Experience"] >= 4)
]

sorted_data = filtered.sort_values(
    "Experience",
    ascending=False
)

result = sorted_data[
    ["Name", "Subject", "Experience"]
]

result

     Name  Subject  Experience
2    Maya  Science           7
0    Asha     Math           5
5  Daniel  Science           4

In [6]:
filtered = df[
    (df["Subject"].isin(["English"]))
    & (df["Experience"] >= 5)
]

sorted_data = filtered.sort_values(
    "Experience",
    ascending=False
)

result = sorted_data[
    ["Name", "Subject", "Experience"]
]

result

   Name  Subject  Experience
4  Sara  English           6

In [14]:
filtered = df[
    (df["Subject"] == "English")
    & (df["Experience"] >= 5)
]

sorted_data = filtered.sort_values(
    "Experience",
    ascending=False
)

result = sorted_data[
    ["Name", "Subject", "Experience"]
]

result

   Name  Subject  Experience
4  Sara  English           6

In [ ]:
filtered = df[
    (df["Subject"] == "English")
    & (df["Experience"] >= 5)
]

sorted_data = filtered.sort_values(
    "Experience",
    ascending=False
)

result = sorted_data[
    ["Name", "Subject", "Experience"]
]

result

In [15]:
df.groupby("Subject")["ExpectedSalary"].mean()

Subject
English    1100.0
Math       1150.0
Science    1375.0
Name: ExpectedSalary, dtype: float64

In [16]:
df.groupby("Subject")["ExpectedSalary"].agg(["mean", "max", "min", "count"])

           mean   max   min  count
Subject
English  1100.0  1300   900      2
Math     1150.0  1200  1100      2
Science  1375.0  1500  1250      2